# Generated by Django 4.1.7 on 2023-03-19 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="Experience",
            new_name="experience",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="Experience_time",
            new_name="experience_time",
        ),
    ]
